# Automatic PR labeling based on changed files
# Format for actions/labeler@v5

# Backend changes
backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**/*'

# Frontend changes
frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**/*'

# Database changes
database:
  - changed-files:
    - any-glob-to-any-file: 
      - 'backend/migrations/**/*'
      - 'backend/src/**/*repository.js'
      - 'seed_db/**/*'

# API changes
api:
  - changed-files:
    - any-glob-to-any-file:
      - 'backend/src/routes/**/*'
      - 'backend/src/modules/**/*-router.js'
      - 'backend/src/modules/**/*-controller.js'

# Configuration changes
config:
  - changed-files:
    - any-glob-to-any-file:
      - '**/.env*'
      - '**/config/**/*'
      - '**/*.config.js'
      - '**/*.config.ts'

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'
      - '.github/**/*.md'

# CI/CD changes
ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/dependabot.yml'
      - '**/Dockerfile'
      - 'docker-compose.yml'

# Dependencies changes
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - '**/package.json'
      - '**/package-lock.json'

# Tests changes
tests:
  - changed-files:
    - any-glob-to-any-file:
      - '**/test/**/*'
      - '**/*.test.js'
      - '**/*.test.ts'
      - '**/*.spec.js'
      - '**/*.spec.ts'

# Security changes
security:
  - changed-files:
    - any-glob-to-any-file:
      - 'backend/src/middlewares/authenticate*.js'
      - 'backend/src/middlewares/csrf*.js'
      - 'backend/src/utils/*password*.js'
      - 'backend/src/utils/jwt*.js'

# Blockchain changes
blockchain:
  - changed-files:
    - any-glob-to-any-file:
      - 'blockchain/**/*'
      - 'backend/src/modules/certificates/blockchain*.js'
      - 'backend/src/modules/certificates/ipfs*.js'

# UI changes
ui:
  - changed-files:
    - any-glob-to-any-file:
      - 'frontend/src/components/**/*'
      - 'frontend/src/assets/**/*'
      - '**/*.css'
      - '**/*.scss'

# Performance changes
performance:
  - changed-files:
    - any-glob-to-any-file:
      - 'backend/src/middlewares/cache*.js'
      - 'backend/src/config/redis.js'
      - '**/optimization/**/*'
